# Generated by Django 3.2.16 on 2024-04-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_congratulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('created_at',)},
        ),
    ]
